Repository copilot-platforms/tasks-app, pull requests merged in 2024-08, with the labels that each got.

#213 OUT-675 Extra scrollbars on Tasks
  src/app/ui/TaskBoard.tsx
  src/components/cards/ListViewTaskCard.tsx
  src/components/cards/TaskCard.tsx
  src/components/cards/TaskColumn.tsx
  src/hoc/CustomLink.tsx
Labels: Simple workflow, QA

#206 OUT-643 | Search result shows duplicate records when searching with last name
  src/types/common.ts
  src/utils/users.ts
Labels: QA

#209 OUT-657 | OUT-655 | CU does not receive email when IU assigns tasks to their company + Notification Email customization
  src/app/api/notification/notification.helpers.ts
  src/app/api/notification/notification.service.ts
  src/app/api/tasks/tasks.service.ts
Labels: QA

#216 OUT-680 Sometimes Assignee shows 'unassigned' on task details page
  src/app/detail/ui/Sidebar.tsx
Labels: Simple workflow

#210 OUT-662 | Deleting task shows error on client side
  src/app/detail/[task_id]/[user_type]/page.tsx
  src/app/detail/ui/TaskEditor.tsx
  src/hoc/RealTime.tsx
  src/utils/redirect.ts
Labels: QA

#219 OUT 661 Default order of tasks should be most recent at the top
  src/app/api/tasks/tasks.service.ts
  src/app/client/page.tsx
  src/app/page.tsx
  src/app/ui/Modal_NewTaskForm.tsx
  src/app/ui/TaskBoard.tsx
  src/redux/features/taskBoardSlice.tsx
  src/types/dto/tasks.dto.ts
  src/utils/sortTask.ts
Labels: Simple workflow

#221 OUT-637 Task title shows in Grey color on task details page on Client side.
  src/app/detail/ui/TaskEditor.tsx
Labels: Simple workflow, QA

#207 OUT-648 | Filter drop-down shows companies even if companies are disabled
  src/app/api/users/users.service.ts
Labels: QA

#211 OUT-649 Filtering area doesn't look good on mobile.
  src/components/buttons/TertiaryBtn.tsx
  src/components/buttonsGroup/FilterButtonsGroup.tsx
  src/components/cards/ClientTaskCard.tsx
  src/components/layouts/FilterBar.tsx
  src/components/searchBar/index.tsx
Labels: QA

#203 OUT-627, OUT-685 No error messages are showing for mandatory field on Task creation pop up
  src/app/ui/NewTaskForm.tsx
  src/components/error/FormHelperText.tsx
  src/components/inputs/Selector.tsx
  src/components/inputs/TextField.tsx
  src/redux/features/createTaskSlice.ts
  src/theme/theme.ts
  src/types/interfaces.ts
  src/types/theme.d.ts
Labels: QA

#244 OUT-733 Default order of tasks should be most recent at the top
  src/app/client/page.tsx
  src/app/client/ui/ClientTaskBoard.tsx
  src/app/page.tsx
  src/app/ui/TaskBoard.tsx
  src/hoc/RealTime.tsx
  src/redux/features/taskBoardSlice.tsx
  src/utils/sortTask.ts
Labels: Simple workflow, QA
