Repository copilot-platforms/tasks-app, pull requests merged in 2024-06, with the labels that each got.

#70 OUT-419 If I start editing a template, then hit Escape (to close), then click New Template, it loads the template I was editing
  src/app/manage-templates/ui/TemplateForm.tsx
  src/app/ui/NewTaskForm.tsx
  src/redux/features/templateSlice.tsx
Labels: bug fixes

#80 OUT-435 Typeahead not working for templates
  src/app/ui/NewTaskForm.tsx
  src/components/inputs/Selector.tsx
Labels: bug fixes

#79 OUT-414 UI Bug when I click on the assignee dropdown and then hit escape
  src/app/ui/NewTaskForm.tsx
  src/components/inputs/Selector.tsx
Labels: bug fixes

#76 OUT 432 Correct placeholder in assignee dropdown
  src/app/detail/ui/Sidebar.tsx
  src/app/ui/NewTaskForm.tsx
  src/components/cards/ListViewTaskCard.tsx
Labels: bug fixes

#74 OUT 426 Hitting escape when I have a task open should take me back to the tasks list view
  src/app/ui/NewTaskForm.tsx
  src/app/ui/TaskBoard.tsx
Labels: bug fixes

#78 OUT 415 UI bugs with dropdown in create task flow
  src/app/ui/NewTaskForm.tsx
  src/components/inputs/Selector.tsx
Labels: bug fixes

#75 OUT 425 UI Element in Task Details View should match status of task
  src/app/detail/[task_id]/[user_type]/page.tsx
  src/app/detail/ui/TaskEditor.tsx
Labels: bug fixes

#73 OUT 430 I shouldn't be able to create a task with an empty title
  src/app/ui/TaskBoard.tsx
  src/types/dto/tasks.dto.ts
Labels: bug fixes

#82 OUT-429 Client-side UI shows "no assignee"
  src/app/api/tasks/[id]/complete/route.ts
  src/app/api/tasks/tasks.controller.ts
  src/app/api/tasks/tasks.service.ts
  src/app/api/users/client/route.ts
  src/app/api/users/users.controller.ts
  src/app/api/users/users.service.ts
  src/app/client/actions.ts
  src/app/client/page.tsx
  src/app/client/ui/ClientTaskBoard.tsx
  src/components/cards/ClientTaskCard.tsx
Labels: bug fixes

#83 OUT-412 When I'm looking at Client Tasks and I hit Filter by, options should match
  src/app/ui/NewTaskForm.tsx
  src/components/layouts/FilterBar.tsx
  src/redux/features/taskBoardSlice.tsx
  src/types/interfaces.ts
Labels: bug fixes

#91 OUT 376 Turn off data caching
  src/app/api/activity-logs/[id]/route.ts
  src/app/api/attachments/attachments.controller.ts
  src/app/api/tasks/tasks.controller.ts
  src/app/api/users/users.controller.ts
  src/app/api/view-settings/viewSettings.controller.ts
  src/app/api/workflow-states/workflowStates.controller.ts
  src/app/client/page.tsx
  src/app/detail/[task_id]/[user_type]/page.tsx
  src/app/layout.tsx
  src/app/manage-templates/page.tsx
  src/app/page.tsx
Labels: bug fixes

#72 OUT-416 File attachment not working on task creation
  src/app/actions.ts
  src/app/api/attachments/attachments.controller.ts
  src/app/api/attachments/attachments.service.ts
  src/app/api/attachments/bulk/route.ts
  src/app/api/tasks/tasks.controller.ts
  src/app/detail/ui/TaskEditor.tsx
  src/app/page.tsx
  src/app/ui/NewTaskForm.tsx
  src/app/ui/TaskBoard.tsx
  src/components/cards/AttachmentCard.tsx
  src/redux/features/createTaskSlice.ts
  src/types/dto/attachments.dto.ts
  src/utils/SupabaseActions.ts
  src/utils/bulkRemoveAttachments.ts
Labels: Advanced feature

#85 OUT-333 Integration - Integrate activity log and comments list
  package.json
  src/app/api/view-settings/viewSettings.service.ts
  src/app/detail/[task_id]/[user_type]/page.tsx
  src/app/detail/ui/ActivityLog.tsx
  src/types/common.ts
  src/utils/getTimeDifference.ts
  yarn.lock
Labels: Advanced feature

#88 OUT 371 API - Email & In-product Notifications for Comments
  prisma/migrations/20240621085459_adds_labels_schema/migration.sql
  prisma/schema.prisma
  src/app/actions.ts
  src/app/api/activity-logs/[id]/route.ts
  src/app/api/activity-logs/services/activity-log.service.ts
  src/app/api/attachments/attachments.controller.ts
  src/app/api/comment/comment.service.ts
  src/app/api/core/types/tasks.ts
  src/app/api/label-mapping/label-mapping.service.ts
  src/app/api/notification/notification.helpers.ts
  src/app/api/notification/notification.service.ts
  src/app/api/tasks/tasks.controller.ts
  src/app/api/tasks/tasks.helpers.ts
  src/app/api/tasks/tasks.service.ts
  src/app/api/upload/route.ts
  src/app/api/users/users.controller.ts
  src/app/api/view-settings/viewSettings.controller.ts
  src/app/api/workflow-states/workflowStates.controller.ts
  src/app/client/actions.ts
  src/app/client/page.tsx
  src/app/detail/[task_id]/[user_type]/actions.ts
  src/app/detail/[task_id]/[user_type]/page.tsx
  src/app/layout.tsx
  src/app/manage-templates/actions.ts
  src/app/manage-templates/page.tsx
  src/app/page.tsx
  src/app/ui/TaskBoard.tsx
  src/components/cards/TaskCard.tsx
  src/hoc/ClientSideStateUpdate.tsx
  src/types/dto/comment.dto.ts
  src/types/dto/tasks.dto.ts
Labels: Advanced feature

#93 OUT-449 Integrate Tapwrite in Tasks Create modal
  package.json
  src/app/detail/ui/styledComponent.tsx
  src/app/ui/NewTaskForm.tsx
  yarn.lock
Labels: Simple workflow

#92 OUT-370 UI - Mentions implementation in Comments
  src/app/api/activity-logs/schemas/CommentAddedSchema.ts
  src/app/detail/[task_id]/[user_type]/page.tsx
  src/app/detail/ui/ActivityLog.tsx
  src/app/detail/ui/Sidebar.tsx
  src/app/detail/ui/styledComponent.tsx
  src/components/cards/CommentCard.tsx
  src/components/inputs/CommentInput.tsx
  src/hoc/ClientSideStateUpdate.tsx
  src/redux/features/taskDetailsSlice.ts
  src/types/dto/comment.dto.ts
  src/types/interfaces.ts
  src/utils/getMentionList.ts
  yarn.lock
Labels: Advanced feature

#98 OUT 466 Cards in list view of board do not match design
  src/app/ui/TaskBoard.tsx
  src/components/cards/ListViewTaskCard.tsx
  src/components/inputs/Selector.tsx
Labels: Simple workflow

#100 OUT 465 No hover effect on task cards
  src/components/cards/TaskCard.tsx
Labels: Simple workflow

#77 OUT-410 When I create a task with no assignee, it doesn't show up on the page immediately
  src/app/detail/ui/ActivityLog.tsx
  src/app/detail/ui/Comments.tsx
  src/app/detail/ui/Sidebar.tsx
  src/app/detail/ui/styledComponent.tsx
  src/app/ui/NewTaskForm.tsx
  src/components/buttons/FilterByAssigneeBtn.tsx
  src/components/cards/ClientTaskCard.tsx
  src/components/cards/CommentCard.tsx
  src/components/cards/ListViewTaskCard.tsx
  src/components/cards/TaskCard.tsx
  src/components/inputs/Selector.tsx
  src/types/interfaces.ts
  src/utils/getAssigneeName.ts
Labels: bug fixes, Simple workflow

#103 OUT 434 Simplify the status dropdown
  src/app/detail/ui/Sidebar.tsx
  src/app/ui/NewTaskForm.tsx
  src/components/inputs/Selector-WorkflowState.tsx
Labels: Simple workflow

#104 OUT 474 React-DnD doesn't work properly on mobile devices
  src/app/ui/TaskBoard.tsx
  src/components/cards/ListViewTaskCard.tsx
  src/components/cards/TaskCard.tsx
  src/hoc/ClientSideStateUpdate.tsx
  src/hoc/DndWrapper.tsx
  src/hoc/DragDropHandler.tsx
Labels: Simple workflow

#106 OUT-473 | Task workflowstate change error in initial phases of application
  src/app/ui/TaskBoard.tsx
Labels: Simple workflow

#108 OUT 475 | OUT-476 Issues with Assignee selector
  src/app/ui/NewTaskForm.tsx
  src/components/inputs/Selector.tsx
Labels: Simple workflow
